Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/focal64"
   config.vm.synced_folder "src/", "/app"
   config.vm.boot_timeout = 600
   config.vm.provider "virtualbox" do |vb|
         vb.gui = false
         vb.memory = "4000"
         vb.cpus = "2"
   end
   config.vm.provision "shell", inline: <<-SHELL
      apt-get update
    SHELL

   config.vm.define "manager" do |manager|
      manager.vm.hostname="manager"
      manager.vm.network "private_network", ip: "192.168.56.10"
      manager.vm.provider "virtualbox" do |vb|
         vb.name = "manager"
      end
   end

   config.vm.define "node01" do |node01|
      node01.vm.hostname="node01"
      node01.vm.network "private_network", ip: "192.168.56.11"
      node01.vm.network "forwarded_port", guest: 80, host: 8080
      node01.vm.provider "virtualbox" do |vb|
         vb.name = "node01"
      end
   end

   config.vm.define "node02" do |node02|
      node02.vm.hostname="node02"
      node02.vm.network "private_network", ip: "192.168.56.12"
      node02.vm.provider "virtualbox" do |vb|
         vb.name = "node02"
      end
  end

end
